name: mad_team_minihead
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4

  image_picker: ^1.1.1
  flutter_animate: ^4.5.0
  flutter_local_notifications: ^13.0.0
  shared_preferences: ^2.0.6
  permission_handler: ^8.3.0

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  provider: ^6.1.2
  firebase_ui_auth: ^1.14.0

  google_ml_kit: ^0.7.0
  google_mlkit_text_recognition: ^0.3.0
  dart_openai: ^5.1.0
  envied: ^0.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
<<<<<<< HEAD
  flutter_gen:
  intl_translation: ^0.20.0
=======
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11
>>>>>>> 2a7ed18bbf253d24c03d92a835dc477c139e60d7

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/l10n/
