// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuAT5TW8M21HoZg1P8hZdKhD5XdH_yBD8',
    appId: '1:1080266264659:web:42c9671e2f9d0f559036a6',
    messagingSenderId: '1080266264659',
    projectId: 'dbbase-team-minihead',
    authDomain: 'dbbase-team-minihead.firebaseapp.com',
    storageBucket: 'dbbase-team-minihead.appspot.com',
    measurementId: 'G-TC22JPHT5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQGDsNHLcuOXKOc5jQRR4XZ8tq-uTGjAI',
    appId: '1:1080266264659:android:eff76fb692358ade9036a6',
    messagingSenderId: '1080266264659',
    projectId: 'dbbase-team-minihead',
    storageBucket: 'dbbase-team-minihead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCIG8xKuNG_O_yds3q3td8kFwLCX2p4xA',
    appId: '1:1080266264659:ios:69573bef4e8552169036a6',
    messagingSenderId: '1080266264659',
    projectId: 'dbbase-team-minihead',
    storageBucket: 'dbbase-team-minihead.appspot.com',
    iosBundleId: 'com.minihead.madTeamMinihead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCIG8xKuNG_O_yds3q3td8kFwLCX2p4xA',
    appId: '1:1080266264659:ios:69573bef4e8552169036a6',
    messagingSenderId: '1080266264659',
    projectId: 'dbbase-team-minihead',
    storageBucket: 'dbbase-team-minihead.appspot.com',
    iosBundleId: 'com.minihead.madTeamMinihead',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuAT5TW8M21HoZg1P8hZdKhD5XdH_yBD8',
    appId: '1:1080266264659:web:24ea49d4dae225849036a6',
    messagingSenderId: '1080266264659',
    projectId: 'dbbase-team-minihead',
    authDomain: 'dbbase-team-minihead.firebaseapp.com',
    storageBucket: 'dbbase-team-minihead.appspot.com',
    measurementId: 'G-4LHRZKQL2S',
  );
}
